language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  
install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=wsstat setup.py test"
after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash)